updated to django 1.10
this fixes error for 
python manage.py fcm_urls 

ImportError: cannot import name 'NoArgsCommand'

This is due to Django 1.10